version: 0.1

phases:
  build:
    commands:
      - docker build -t docker-grafana .
      - docker tag docker-grafana:latest 861716072457.dkr.ecr.us-east-1.amazonaws.com/docker-grafana:latest 
      - docker push 861716072457.dkr.ecr.us-east-1.amazonaws.com/docker-grafana:latest
