version: 0.1

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region us-east-1)
  build:
    commands:
      - docker build -t docker-grafana .
      - docker tag docker-grafana:latest 861716072457.dkr.ecr.us-east-1.amazonaws.com/docker-grafana:latest 
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 861716072457.dkr.ecr.us-east-1.amazonaws.com/docker-grafana:latest
